connect-info:
  host: localhost
  port: 19090
  uripath: /agent

control-value:
  numOfVirtualDevices: 10 # [TODO] if define 0 then 'variable-input-sample-list' node list size
  sendDelayMills: 5000
  
payload:
  str: '{"type":"common","executetime":"2019-11-20 08:43:53.7872659 +0900 KST m=+0.294016801",
    "deviceid":"SERVER03","deviceip":"10.1.12.52","rmem":88,"smem":76.02713028339298,"cpu":9.525688863372388,
    "diskinfo":[{"path":"C:","usedPercent":91.42866823451054}]}'
  variable-part: deviceid

variable-input-sample-list: 
  - server01
  - server02
  - server03
  - server04
  - server05
  - server06
  - server07
  - server08
  - server09
  - server10
  - server11
  - server12
  - server13
  - server14
  - server15
  - server16
  - server17
  - server18
  - server19
  - server20
  - server21
  - server22
  - server23
  - server24
  - server25
  - server26
  - server27
  - server28
  - server29
  - server30
  - server31
  - server32
  - server33
  - server34
  - server35
  - server36
  - server37
  - server38
  - server39
  - server40
  - server41
  - server42
  - server43
  - server44
  - server45
  - server46
  - server47
  - server48
  - server49
  - server50
  - server51
  - server52
  - server53
  - server54
  - server55
  - server56
  - server57
  - server58
  - server59
  - server60
  - server61
  - server62
  - server63
  - server64
  - server65
  - server66
  - server67
  - server68
  - server69
  - server70
  - server71
  - server72
  - server73
  - server74
  - server75
  - server76
  - server77
  - server78
  - server79
  - server80
  - server81
  - server82
  - server83
  - server84
  - server85
  - server86
  - server87
  - server88
  - server89
  - server90
  - server91
  - server92
  - server93
  - server94
  - server95
  - server96
  - server97
  - server98
  - server99
  - server100
  - server101
  - server102
  - server103
  - server104
  - server105
  - server106
  - server107
  - server108
  - server109
  - server110
  - server111
  - server112
  - server113
  - server114
  - server115
  - server116
  - server117
  - server118
  - server119
  - server120
  - server121
  - server122
  - server123
  - server124
  - server125
  - server126
  - server127
  - server128
  - server129
  - server130
  - server131
  - server132
  - server133
  - server134
  - server135
  - server136
  - server137
  - server138
  - server139
  - server140
  - server141
  - server142
  - server143
  - server144
  - server145
  - server146
  - server147
  - server148
  - server149
  - server150
  - server151
  - server152
  - server153
  - server154
  - server155
  - server156
  - server157
  - server158
  - server159
  - server160
  - server161
  - server162
  - server163
  - server164
  - server165
  - server166
  - server167
  - server168
  - server169
  - server170
  - server171
  - server172
  - server173
  - server174
  - server175
  - server176
  - server177
  - server178
  - server179
  - server180
  - server181
  - server182
  - server183
  - server184
  - server185
  - server186
  - server187
  - server188
  - server189
  - server190
  - server191
  - server192
  - server193
  - server194
  - server195
  - server196
  - server197
  - server198
  - server199
  - server200
  - server201
  - server202
  - server203
  - server204
  - server205
  - server206
  - server207
  - server208
  - server209
  - server210
  - server211
  - server212
  - server213
  - server214
  - server215
  - server216
  - server217
  - server218
  - server219
  - server220
  - server221
  - server222
  - server223
  - server224
  - server225
  - server226
  - server227
  - server228
  - server229
  - server230
  - server231
  - server232
  - server233
  - server234
  - server235
  - server236
  - server237
  - server238
  - server239
  - server240
  - server241
  - server242
  - server243
  - server244
  - server245
  - server246
  - server247
  - server248
  - server249
  - server250
  - server251
  - server252
  - server253
  - server254
  - server255
  - server256
  - server257
  - server258
  - server259
  - server260
  - server261
  - server262
  - server263
  - server264
  - server265
  - server266
  - server267
  - server268
  - server269
  - server270
  - server271
  - server272
  - server273
  - server274
  - server275
  - server276
  - server277
  - server278
  - server279
  - server280
  - server281
  - server282
  - server283
  - server284
  - server285
  - server286
  - server287
  - server288
  - server289
  - server290
  - server291
  - server292
  - server293
  - server294
  - server295
  - server296
  - server297
  - server298
  - server299
  - server300
  - server301
  - server302
  - server303
  - server304
  - server305
  - server306
  - server307
  - server308
  - server309
  - server310
  - server311
  - server312
  - server313
  - server314
  - server315
  - server316
  - server317
  - server318
  - server319
  - server320
  - server321
  - server322
  - server323
  - server324
  - server325
  - server326
  - server327
  - server328
  - server329
  - server330
  - server331
  - server332
  - server333
  - server334
  - server335
  - server336
  - server337
  - server338
  - server339
  - server340
  - server341
  - server342
  - server343
  - server344
  - server345

